const bikes = [
  { id: 1, name: 'VoltRide City Pro', slug: 'voltride-city-pro', categoryId: 1, category: { id: 1, name: 'Scooters', slug: 'scooters', description: 'Electric scooters', imageUrl: null }, price: 1299, rangeKm: 80, topSpeedKph: 45, motorWatts: 500, batteryCapacityWh: 480, weightKg: 14.5, description: 'The perfect urban commuter scooter with long range and smart connectivity features.', shortDescription: 'Smart urban scooter with 80km range', imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600', galleryUrls: [], features: ['LED Lighting', 'App Connected', 'USB Charging', 'Anti-theft Alarm'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() },
  { id: 2, name: 'ThunderBolt X1', slug: 'thunderbolt-x1', categoryId: 2, category: { id: 2, name: 'Motorcycles', slug: 'motorcycles', description: 'Electric motorcycles', imageUrl: null }, price: 4999, rangeKm: 200, topSpeedKph: 120, motorWatts: 5000, batteryCapacityWh: 7200, weightKg: 185, description: 'High-performance electric motorcycle delivering an exhilarating ride experience.', shortDescription: 'High-performance electric motorcycle', imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=600', galleryUrls: [], features: ['Fast Charging', 'Regenerative Braking', 'ABS', 'Traction Control'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() },
  { id: 3, name: 'EcoGlide Mini', slug: 'ecoglide-mini', categoryId: 3, category: { id: 3, name: 'Mopeds', slug: 'mopeds', description: 'Electric mopeds', imageUrl: null }, price: 799, rangeKm: 50, topSpeedKph: 35, motorWatts: 250, batteryCapacityWh: 280, weightKg: 12, description: 'Lightweight and affordable electric moped perfect for short city trips.', shortDescription: 'Affordable lightweight electric moped', imageUrl: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=600', galleryUrls: [], features: ['Removable Battery', 'LED Display', 'Phone Mount'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
  { id: 4, name: 'ZenSpeed Sport', slug: 'zenspeed-sport', categoryId: 4, category: { id: 4, name: 'Sport Bikes', slug: 'sport-bikes', description: 'Electric sport bikes', imageUrl: null }, price: 7999, rangeKm: 180, topSpeedKph: 150, motorWatts: 8000, batteryCapacityWh: 9600, weightKg: 195, description: 'Track-inspired electric sport bike with cutting-edge performance.', shortDescription: 'Track-inspired electric sport bike', imageUrl: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=600', galleryUrls: [], features: ['Sport Mode', 'Quick Charge', 'Digital Dashboard', 'Adjustable Suspension'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() },
  { id: 5, name: 'UrbanFly Lite', slug: 'urbanfly-lite', categoryId: 1, category: { id: 1, name: 'Scooters', slug: 'scooters', description: 'Electric scooters', imageUrl: null }, price: 899, rangeKm: 60, topSpeedKph: 40, motorWatts: 350, batteryCapacityWh: 360, weightKg: 13, description: 'Compact and stylish electric scooter for daily city commuting.', shortDescription: 'Compact city electric scooter', imageUrl: 'https://images.unsplash.com/photo-1555861496-0666c8981751?w=600', galleryUrls: [], features: ['Foldable Design', 'LED Lights', 'Cruise Control'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
  { id: 6, name: 'PowerMax 3000', slug: 'powermax-3000', categoryId: 2, category: { id: 2, name: 'Motorcycles', slug: 'motorcycles', description: 'Electric motorcycles', imageUrl: null }, price: 3499, rangeKm: 160, topSpeedKph: 100, motorWatts: 3000, batteryCapacityWh: 5400, weightKg: 165, description: 'Versatile electric motorcycle for both city and highway riding.', shortDescription: 'Versatile city and highway motorcycle', imageUrl: 'https://images.unsplash.com/photo-1547549082-6bc09f2049ae?w=600', galleryUrls: [], features: ['Dual Mode', 'GPS Navigation', 'Heated Grips', 'Bluetooth'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() }
];
export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  const { id } = req.query;
  const bike = bikes.find(b => b.id === Number(id));
  if (!bike) return res.status(404).json({ error: 'not_found', message: 'Bike not found' });
  res.status(200).json(bike);
}
