export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Content-Type', 'application/json');
  const { categoryId, minPrice, maxPrice, featured } = req.query;
  const ekoTejas = { id: 4, name: 'Eko Tejas', slug: 'eko-tejas', description: 'Eko Tejas electric vehicles', imageUrl: null };
  const venumotors = { id: 5, name: 'Venumotors', slug: 'venumotors', description: 'Venumotors electric vehicles', imageUrl: null };
  let bikes = [
    { id: 9, name: 'Eko Tejas Axel', slug: 'eko-tejas-axel', categoryId: 4, category: ekoTejas, price: 55000, rangeKm: 100, topSpeedKph: 25, motorWatts: 250, batteryCapacityWh: 2160, weightKg: 78.0, shortDescription: 'Everyday commuter - 25 km/h top speed. No DL required. Lead Acid & Li-Ion variants up to 100 km.', imageUrl: '/images/models/axel-front.png', galleryUrls: ['/images/models/axel-front.png'], features: ['250W BLDC Hub Motor','12-Tube Controller','3-Speed Modes (25 km/h top speed)','Front Disc Brake, Rear Drum Brake','Telescopic Front Suspension','Hydraulic Rear Suspension','LED Lighting','Digital LCD Display','20L Boot Space','270mm Ground Clearance','2 PAX + Luggage Capacity','No Driving Licence Required','No Registration Required','Lead Acid Option - 44 to 65 km','Li-Ion Option - 65 to 100 km','48V / 60V Battery Variants'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 10, name: 'Eko Tejas Axel Pro', slug: 'eko-tejas-axel-pro', categoryId: 4, category: ekoTejas, price: 75000, rangeKm: 100, topSpeedKph: 25, motorWatts: 250, batteryCapacityWh: 2160, weightKg: 78.0, shortDescription: 'Premium Axel with dual-tone styling - 25 km/h top speed. No DL required. Up to 100 km on Li-Ion.', imageUrl: '/images/models/axel-pro-front.png', galleryUrls: ['/images/models/axel-pro-front.png'], features: ['250W BLDC Hub Motor','12-Tube Controller','3-Speed Modes (25 km/h top speed)','Front Disc Brake, Rear Drum Brake','Telescopic Front Suspension','Hydraulic Rear Suspension','LED Lighting','Digital LCD Display','20L Boot Space','270mm Ground Clearance','2 PAX + Luggage Capacity','Premium Dual-Tone Body Graphics','No Driving Licence Required','No Registration Required','Lead Acid Option - 44 to 65 km','Li-Ion Option - 65 to 100 km','48V / 60V Battery Variants'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 11, name: 'Venumotors Spot', slug: 'venumotors-spot', categoryId: 5, category: venumotors, price: 52000, rangeKm: 60, topSpeedKph: 72, motorWatts: 1920, batteryCapacityWh: 0, weightKg: 25.0, shortDescription: 'Sporty city scooter with bold angular styling - 45 to 60 km range. No DL required.', imageUrl: '/images/models/spot-new.jpg', galleryUrls: ['/images/models/spot-new.jpg'], features: ['1920W Motor','Bold Angular Design','45-60 km Range','No DL Required','Digital Display','LED Lighting'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 12, name: 'Venumotors Thunder', slug: 'venumotors-thunder', categoryId: 5, category: venumotors, price: 72000, rangeKm: 70, topSpeedKph: 70, motorWatts: 1920, batteryCapacityWh: 0, weightKg: 25.0, shortDescription: 'Bold steel-blue scooter - 65-70 km range. No DL required. Keyless entry & cruise mode.', imageUrl: '/images/models/thunder-new.jpg', galleryUrls: ['/images/models/thunder-new.jpg'], features: ['1920W Motor','Keyless Entry','Cruise Mode','65-70 km Range','No DL Required','LED Lighting','Digital Display'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 13, name: 'Venumotors Icon', slug: 'venumotors-icon', categoryId: 5, category: venumotors, price: 78000, rangeKm: 90, topSpeedKph: 25, motorWatts: 2304, batteryCapacityWh: 0, weightKg: 82.0, shortDescription: 'Long-range icon - 80 to 90 km per charge. Bold graphics in teal & red. No DL required.', imageUrl: '/images/models/icon-new.jpg', galleryUrls: ['/images/models/icon-new.jpg'], features: ['2304W Motor','80-90 km Range','Bold Teal & Red Graphics','No DL Required','Digital Display','LED Lighting'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 14, name: 'Venumotors E-Fly', slug: 'venumotors-e-fly', categoryId: 5, category: venumotors, price: 82000, rangeKm: 90, topSpeedKph: 25, motorWatts: 2304, batteryCapacityWh: 0, weightKg: 80.0, shortDescription: 'Flagship long-range scooter - 80 to 90 km per charge. Teal & red. No DL required.', imageUrl: '/images/models/efly-new.jpg', galleryUrls: ['/images/models/efly-new.jpg'], features: ['2304W Motor','80-90 km Range','Flagship Model','No DL Required','Digital Display','LED Lighting'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 15, name: 'Eko Tejas Jatayu', slug: 'eko-tejas-jatayu', categoryId: 4, category: ekoTejas, price: 82000, rangeKm: 90, topSpeedKph: 25, motorWatts: 2520, batteryCapacityWh: 0, weightKg: 85.0, shortDescription: 'Bold flagship scooter - up to 90 km+ in Orange, Teal, Navy & Rose Gold. No DL required.', imageUrl: '/images/models/jatayu-orange-front.jpg', galleryUrls: ['/images/models/jatayu-orange-front.jpg','/images/models/jatayu-teal-front.jpg','/images/models/jatayu-blue-front.jpg','/images/models/jatayu-rosegold.jpg'], features: ['2520W Motor','Up to 90 km Range','Available in Orange, Teal, Navy & Rose Gold','No DL Required','Digital Display','LED Lighting','Premium Build'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() },
    { id: 17, name: 'Eko Tejas Priv Mini', slug: 'eko-tejas-priv-mini', categoryId: 4, category: ekoTejas, price: 63000, rangeKm: 140, topSpeedKph: 75, motorWatts: 1500, batteryCapacityWh: 2520, weightKg: 90.0, shortDescription: 'Retro-premium scooter - 1500W motor, 75 km/h top speed. Up to 140 km range on 72V Li-Ion.', imageUrl: '/images/models/priv-mini-front.png', galleryUrls: ['/images/models/priv-mini-front.png'], features: ['1500W Motor','75 km/h Top Speed','Up to 140 km Range','72V Li-Ion Battery','Retro Premium Design','Digital Display','LED Lighting'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() },
    { id: 18, name: 'Eko Tejas Astra', slug: 'eko-tejas-astra', categoryId: 4, category: ekoTejas, price: 95000, rangeKm: 100, topSpeedKph: 25, motorWatts: 3024, batteryCapacityWh: 0, weightKg: 88.0, shortDescription: 'Adventure-styled scooter - triple LED headlamp, golden fork, up to 100 km+. No DL required.', imageUrl: '/images/models/astra-front.png', galleryUrls: ['/images/models/astra-front.png'], features: ['3024W Motor','Triple LED Headlamp','Golden Fork','Up to 100 km Range','Adventure Styling','No DL Required','Digital Display'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() },
    { id: 19, name: 'Eko Tejas Max', slug: 'eko-tejas-max', categoryId: 4, category: ekoTejas, price: 72000, rangeKm: 100, topSpeedKph: 25, motorWatts: 2520, batteryCapacityWh: 0, weightKg: 85.0, shortDescription: 'Sporty V-LED scooter in 8 bold colours - up to 100 km+ range. No DL required.', imageUrl: '/images/models/max-front.png', galleryUrls: ['/images/models/max-front.png'], features: ['2520W Motor','V-Shaped LED Design','8 Colour Options','Up to 100 km Range','No DL Required','Digital Display','LED Lighting'], isFeatured: true, inStock: true, createdAt: new Date().toISOString() },
    { id: 20, name: 'Eko Tejas Shero Neo', slug: 'eko-tejas-shero-neo', categoryId: 4, category: ekoTejas, price: 68000, rangeKm: 80, topSpeedKph: 25, motorWatts: 2160, batteryCapacityWh: 0, weightKg: 82.0, shortDescription: 'Stylish women-first scooter - available in Pink, Teal, White & Grey. No DL required.', imageUrl: '/images/models/shero-neo-front.png', galleryUrls: ['/images/models/shero-neo-front.png','/images/models/shero-neo-pink-front.jpg','/images/models/shero-neo-teal-front.jpg','/images/models/shero-neo-grey.jpg'], features: ['2160W Motor','Up to 80 km Range','Women-First Design','Available in Pink, Teal, White & Grey','No DL Required','Digital Display','LED Lighting'], isFeatured: false, inStock: true, createdAt: new Date().toISOString() }
  ];
  if (categoryId) bikes = bikes.filter(b => b.categoryId === Number(categoryId));
  if (minPrice) bikes = bikes.filter(b => b.price >= Number(minPrice));
  if (maxPrice) bikes = bikes.filter(b => b.price <= Number(maxPrice));
  if (featured === 'true') bikes = bikes.filter(b => b.isFeatured);
  res.status(200).json(bikes);
}
